# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push
  # Triggers the workflow on push or pull request events but only for the main branch
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  my-job:
    name: My Code
    runs-on: ubuntu-latest
    steps:
      - name: http
        run: |
          curl 'https://oapi.dingtalk.com/robot/send?access_token=9136bbe769399276035302f248141747e2d39b9a5d8c961a5dfee0c1ebf4fd9f' -H 'Content-Type: application/json' -d '{ "msgtype": "markdown", "markdown": { "text": "# 打卡成功. \n ### User: ${{ github.actor }} \n ### Sha: ${{ github.sha }}", "title": "打卡成功... "} }'
    
